CREATE TABLE Employees(
	eid BIGSERIAL PRIMARY KEY,
	did INTEGER NOT NULL,
	resignedDate DATE,
	ename TEXT,
	email TEXT NOT NULL UNIQUE,
	contact1 INTEGER,
	contact2 INTEGER,
	contact3 INTEGER,
	FOREIGN KEY (did) REFERENCES Departments(did) ON DELETE NO ACTION;
);

CREATE TABLE Junior(
	eid BIGSERIAL PRIMARY KEY,
	FOREIGN KEY (eid) REFERENCES Employees(eid) ON DELETE CASCADE;

);

CREATE TABLE Booker(
	eid BIGSERIAL PRIMARY KEY,
	FOREIGN KEY (eid) REFERENCES Employees(eid) ON DELETE CASCADE
);

CREATE TABLE Senior(
	eid BIGSERIAL PRIMARY KEY,
	FOREIGN KEY (eid) REFERENCES Booker(eid) ON DELETE CASCADE
);

CREATE TABLE Manager(
	eid BIGSERIAL PRIMARY KEY,
	FOREIGN KEY (eid) REFERENCES Booker(eid) ON DELETE CASCADE
);