CREATE TABLE Employees(
	eid INTEGER PRIMARY KEY,
	did INTEGER,
	resignedDate DATE,
	ename TEXT,
	email TEXT UNIQUE,
	contact1 INTEGER,
	contact2 INTEGER,
	contact3 INTEGER,
	FOREIGN KEY (did) REFERENCES Departments(did) ON DELETE NO ACTION;
);

CREATE TABLE Junior(
	eid INTEGER PRIMARY KEY,
	FOREIGN KEY (eid) REFERENCES Employees(eid) ON DELETE CASCADE;

);

CREATE TABLE Booker(
	eid INTEGER PRIMARY KEY,
	FOREIGN KEY (eid) REFERENCES Employees(eid) ON DELETE CASCADE
);

CREATE TABLE Senior(
	eid INTEGER PRIMARY KEY,
	FOREIGN KEY (eid) REFERENCES Booker(eid) ON DELETE CASCADE
);

CREATE TABLE Manager(
	eid INTEGER PRIMARY KEY,
	FOREIGN KEY (eid) REFERENCES Booker(eid) ON DELETE CASCADE
);