CREATE TABLE Employees(
	eid INTEGER PRIMARY KEY,
	did INTEGER,
	resignedDate DATE,
	ename TEXT,
	email TEXT UNIQUE,
	contact1 INTEGER,
	contact2 INTEGER,
	contact3 INTEGER,
	FOREIGN KEY (did) REFERENCES Departments(did) ON DELETE NO ACTION;
);

CREATE TABLE Junior(
	eid INTEGER PRIMARY KEY,
	FOREIGN KEY (eid) REFERENCES Employees(eid) ON DELETE CASCADE;

);

CREATE TABLE Booker(
	eid INTEGER PRIMARY KEY,
	FOREIGN KEY (eid) REFERENCES Employees(eid) ON DELETE CASCADE
);

CREATE TABLE Senior(
	eid INTEGER PRIMARY KEY,
	FOREIGN KEY (eid) REFERENCES Booker(eid) ON DELETE CASCADE
);

CREATE TABLE Manager(
	eid INTEGER PRIMARY KEY,
	FOREIGN KEY (eid) REFERENCES Booker(eid) ON DELETE CASCADE
);

CREATE TABLE Departments(
INT did PRIMARY KEY
TEXT dname
);

CREATE TABLE HealthDeclaration(
DATE declareDate
TEXT temp
INT fever
PRIMARY KEY(eid, declareDate)
FOREIGN KEY (eid) REFERENCES Employees(eid) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE MeetingRoom (
  room INTEGER,
  floor INTEGER,
  rname TEXT,
  did INTEGER,
  PRIMARY KEY (floor, room),
  FOREIGN KEY (did) REFERENCES DEPARTMENTS (did) ON DELETE CASCADE ON UPDATE CASCADE
)